import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./styles/globals.css";
import BottomMenuBar from "@/components/layout/BottomMenuBar";

const latoFont = Lato({
  variable: "--font-lato",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${latoFont.variable} antialiased`}>
        {children}
        <BottomMenuBar />
      </body>
    </html>
  );
}
